server:
  port: 8086

spring:
  application:
    name: notification-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:om.service.notification.event.OrderPlacedEvent
    consumer:
      group-id: notificationId

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka